### PR TITLE
Set Krylov solver tolerances in non-linear solver parameters

### PR DESCRIPTION
**Pull request by jrmaddison**
This sets the tolerances to the currently used PETSc defaults, but smaller tolerances may be needed.

### CODE REVIEW

**Review by bearecinos — APPROVED** [review]
This one is ready to merge I already tested the branch with several experiments and all the pytests

**Comment by jrmaddison** [comment]
I think we should choose a smaller default relative tolerance. I'd suggest `1.0e-8` or smaller.

**Comment by bearecinos** [comment]
See PR #124

**Comment by bearecinos** [comment]
closing this as this was merge in PR #124

**Pull request closed without merging**
